[package]
name = "meta-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.9", features = ["derive"] }
env_logger = "0.11.3"
lazy_static = "1.5.0"
strum = { version = "0.26.3", features = ["derive"] }
thiserror = "1.0.63"
